baseURL: https://bmakuntima.netlify.app
languageCode: en-us
title: Makuntima | Bazar Beneficente 
theme: roxo-hugo
summarylength: 25
menu:
  nav:
    - name: Visão Geral
      url: ''
      weight: 1
    - name: Sobre Nós
      url: about
      weight: 2
    - name: Peças á Venda
      url: portfolio
      weight: 3
    - name: Projectos
      url: blog
      weight: 4
    - name: Conecte-se Conosco
      url: contact
      weight: 5
params:
  author: StaticMania
  banner:
    background_image: images/backgrounds/colors-background.jpg
    enable: yes
    heading: Bazar Beneficente Makuntima
    primary_button: O nosso trabalho
    primary_button_url: portfolio
    secondary_button: Conecte-se conosco
    secondary_button_url: contact
    tagline: Do nosso coração para o das comunidades
  call_to_action:
    background_image: images/backgrounds/cta-background.jpg
    enable: yes
    primary_button: Conecte-se conosco
    primary_button_url: contact
    secondary_button: Peças á venda
    secondary_button_url: portfolio
    title: Seja um Parceiro
  contactForm:
    placeholder_about_the_project: Deixe aqui sua mensagem
    placeholder_email: Email
    placeholder_first_name: Nome
    placeholder_last_name: Sobrenome
    placeholder_project_type: Tipo de Projecto
    projectType:
      - title: Bazar
        value: gd
      - title: Outros
        value: wd
    send_message: Send Message
  dateFormat: 26 FEB 1994
  description: Roxo Hugo themes | Design Agency Template by StaticMania
  footer:
    contactInfo:
      address: Kukala-Kyaku, Soyo, Zaire, Angola
      email: 'magracesmile@gmail.com'
      title: Contactos
    service:
      description: Projectos virados ao apoio da criança Angolana<br>Trabalhamos com as comunidades<br>Vencemos cada desafio com fé, foco e determinação
      title: 'Apoiamos crianças em comunidades carentes:'
    sitemap:
      link:
        - name: Visão Geral
          url: about
        - name: Peças a Venda
          url: portfolio
        - name: Projectos
          url: blog
        - name: Conecte-se conosco
          url: contact
      title: Mapa do Website
    social:
      link:
        - name: Facebook
          url: '#'
        - name: Instagram
          url: '#'
        - name: 
          url: '#'
        - name: 
          url: '#'
      title: Social Media
  formspreeFormUrl: https://formspree.io/myykjpje
  googleAnalitycsID: Your ID
  logo: images/team-maktima.png
  navAction:
    name: Get in touch
    status: yes
    url: 'magracesmile@gmail.com'
  portfolio:
    enable: yes
    subtitle: Sonhamos em levar o Bazar Makuntima para as 18 províncias de Angola.
    title: Nosso trabalho mais recente
